// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Installation struct {
	Name string
	Path string
	Type string
}

type InstallationType struct {
	Name string
}
